separated rom kitchen from htcflasher makefile fixed some stuff in the kitchen

diff --git a/trunk/RomKitchen/lrk-preload b/trunk/RomKitchen/lrk-preload
--- a/trunk/RomKitchen/lrk-preload
+++ b/trunk/RomKitchen/lrk-preload
@@ -12,8 +12,8 @@
 
 export VERSION=1.0
 
-TOOLS="/usr/share/LinuxRomKitchen/"
-APPS="$TOOLS/rgucomp.exe $TOOLS/ImgfsFromNb.exe $TOOLS/ImgfsFromDump.exe $TOOLS/ImgfsToNb.exe $TOOLS/NBMerge.exe $TOOLS/RomMaster.exe $TOOLS/dumprom.exe"
+TOOLS="/usr/share/LinuxRomKitchen"
+APPS="$TOOLS/rgucomp.exe $TOOLS/ImgfsFromNb.exe $TOOLS/ImgfsFromDump.exe $TOOLS/ImgfsToNb.exe $TOOLS/NBMerge.exe $TOOLS/RomMaster.exe $TOOLS/dumprom.exe $TOOLS/cereg400.dll $TOOLS/cecompr_nt.dll"
 
 ZENITY=`which zenity`
 GTKDIALOG=""
@@ -69,8 +69,8 @@ if ! [ -e $TOOLS ]; then
 fi
 
 for app in $APPS ; do
-	if ! [ -e $APP ]; then
-		error "ERROR: $APP does not exist"
+	if ! [ -e $app ]; then
+		error "ERROR: $app does not exist"
 		exit 1
 	fi
 done
@@ -87,6 +87,12 @@ Hint: http://lcab.move-to-cork.com/"
 fi
 
 if [ "`which dsminfo`" = "" ]; then
+	error "ERROR: dsminfo is not installed
+Hint: Make sure you have installed latest version of htc-flasher"
+	exit 1
+fi
+
+if [ "`which dsmbuild`" = "" ]; then
 	error "ERROR: dsminfo is not installed
 Hint: Make sure you have installed latest version of htc-flasher"
 	exit 1
@@ -122,13 +128,18 @@ Hint: Make sure you have installed latest version of htc-flasher"
 	exit 1
 fi
 
-if [ "`which gedit`" = "" ]; then
-	error "ERROR: gedit is not installed"
+if [ "`which cabextract`" = "" ]; then
+	error "ERROR: cabextract is not installed"
 	exit 1
 fi
 
-if [ "`which cabextract`" = "" ]; then
-	error "ERROR: cabextract is not installed"
+if [ "`which dos2unix`" = "" ]; then
+	error "ERROR: dos2unix is not installed"
+	exit 1
+fi
+
+if [ "`which iconv`" = "" ]; then
+	error "ERROR: iconv is not installed"
 	exit 1
 fi
 
